// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhikyyjqiwejpfyxalpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoaWt5eWpxaXdlanBmeXhhbHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzIyMzksImV4cCI6MjA2NDEwODIzOX0.Tc-ZACIk2X8fYfsjU0mr2A2KrVMw8nrGpKrpSuy1iE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);